### ISSUE TITLE
Should we add any information about early voting?

### ISSUE THREAD

**Issue by abrauninger** [VotingVoices/chorus#118]
Currently the app makes no mention of early voting, which is a common way to vote in many states.

**Comment by abrauninger** [comment]
I like the idea.  But I think the exact wording of "would you like to try to vote early or by absentee ballot?" seems to present a choice of one or the other (and what if I want to do neither).

Perhaps instead of Yes/No we could have three answers:

Vote on Election Day | Vote early | Vote by absentee ballot

(All of these strings might be too long to fit, but that's the idea at least.)

Maybe we could just word the question, "What method do you plan to use to vote?" or just "How do you plan on voting?"

I would also remove "try to" unless we think it's important.

**Comment by seattlehedgehog** [comment]
I know - I was thinking of three choices as well, but was wondering if it would slow folks down too much. If we go with "How do you plan on voting?", it will definitely need to come after the zip code splitter for the polls path. 

I'm with you on the length of those strings. How about "At the polls", "Vote early" and "Absentee". Think that's enough info? As for 'try', it was there because not all states allow for early and/or absentee voting. I think we take care of that with asking how they 'plan' to vote.

**Comment by abrauninger** [comment]
We could also determine from the ZIP code whether their state has early voting.  (That would take more work, though.)

**Comment by seattlehedgehog** [comment]
Agreed. That would be awesome if we have time.

**Comment by abrauninger** [comment]
Implemented in 297a1c6.

@seattlehedgehog I implemented slightly different text for the plan-step for absentee vs. early voting:

Absentee:
"A convenient way to go! Just remember to check on postage and your mailing deadline."

Early voting:
"A convenient way to go! Learn about early voting and find the rules for your state."

Sound good?

**Comment by seattlehedgehog** [comment]
Perfect! Thank you!
