### ISSUE TITLE
Remove When We All Vote link and replace with copy

### ISSUE THREAD

**Issue by seattlehedgehog** [VotingVoices/chorus#119]
Let's remove the sentiment link and update the copy as follows:

Excited | Put those feelings toward voting action | You're excited and that's great! Take your enthusiasm all the way to the polls or ballot box.
Concerned | Put those feelings toward voting action | You're feeling concerned--we get it! These are complicated times. You'll feel better after a visit to the polls or ballot box.
Shocked | Put those feelings toward action | You're feeling shocked--we get it! These are complicated times. You'll feel better after a visit to the polls or ballot box.
Angry | Put those feelings toward action | You're feeling angry--we get it! These are complicated times. You'll feel better after a visit to the polls or ballot box.
Meh | Put those feelings toward action | Feeling ambivalent? Your voting plans are taking shape--now get out there and vote!

**Comment by abrauninger** [comment]
Does "visit to the polls or ballot box" make sense in vote-by-mail states like WA?

**Comment by abrauninger** [comment]
New copy (after discussing with @seattlehedgehog):

Excited | Put those feelings toward voting action | You're excited and that's great! Take your enthusiasm all the way to the polls or ballot box.
Concerned | Put those feelings toward voting action | You're feeling concerned -- we get it! These are complicated times. You'll feel better after you get out there and vote.
Shocked | Put those feelings toward action | You're feeling shocked -- we get it! These are complicated times. You'll feel better after you get out there and vote.
Angry | Put those feelings toward action | You're feeling angry -- we get it! These are complicated times. You'll feel better after you get out there and vote.
Meh | Put those feelings toward action | Feeling ambivalent? Your voting plans are taking shape -- now get out there and vote!

@seattlehedgehog what do you think?  I'm thinking we still keep "polls or ballot box" for the first CTA ("take your enthusiasm...") since I'm not sure how to word it with "get out there and vote."

**Comment by abrauninger** [comment]
@seattlehedgehog does "Put those feelings toward action" make sense for the "Meh" response?

**Comment by abrauninger** [comment]
Removed the link in 342bfbd.  I've filed issue #120 to track the issue where "Put those feelings toward action" might not make sense when someone has said they're feeling Meh.
