### ISSUE TITLE
Should the Plan page give more credit for what users have already done?

### ISSUE THREAD

**Issue by abrauninger** [VotingVoices/chorus#65]
I demo'd the app last night to a friend of mine, and one of her pieces of feedback is that the Plan page should give more credit to the user for work they've already done (such as, registering to vote, requesting their ballot, researching issues, etc.).

In other words, rather than just presenting a to-do list, present the to-do list in addition to an "already-done" list.  This might be a more positive experience for the user because it would give them positive feedback and encouragement for what they've already done.

**Comment by seattlehedgehog** [comment]
I like this idea and was already going to suggest changing the "Congratulations, here is your" heading since it doesn't seem to flow easily into the Vote Plan script font. I wonder if it would help if we changed it to something like this: "Nice work! Just you're well on your way to making your vote and voice heard. Here are some next steps to help you stick the landing." It's significantly longer and might look better under the "Vote Plan" header (especially when we drop the start over to the bottom). I'm also adding a personal suggestion that we make the entire plan page background white to see if it make scrolling down more obvious.

**Comment by abrauninger** [comment]
I just got feedback from a coworker that was along the same lines as my friend's feedback from last night: It would be great if the Plan page showed what you had already done.

**Comment by seattlehedgehog** [comment]
From Jan: 

Now you've got everything you need to take voting action. You've done the prep to get your info on registration, your ballot, who/what/where, voting logistics, and more--way to go! Your voice matters. The time is now. Get out there and vote the midterms!

**Comment by abrauninger** [comment]
I think we can close this issue for now; not sure there's much actionable feedback left here.
